services:
  database:
    image: mysql:latest 
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:  
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase  
      MYSQL_USER: user  
      MYSQL_PASSWORD: password 
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      dockerfile: AppDockerfile
    env_file:
      - .env
    ports:
      - "3010:3010"
    depends_on:
      - database
    volumes:
      - ./src:/app/src
    command: bash -c "npm run start"

volumes:
  mysql-data:
