version: '1.0'

services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: efficy
    volumes:
      - pg-data:/var/lib/postgresql/data


  app:
    build:
      dockerfile: AppDockerfile
    env_file:
      - .env
    ports:
      - "3010:3010"
    depends_on:
      - database
    volumes:
      - ./src:/app/src
    command: bash -c "npm run start"

volumes:
  pg-data: